COOKING_MIN_TIME = 1
INGREDIENT_MAX_LENGTH = 128
INGREDIENT_MIN_AMOUNT = 1
INGREDIENT_UNIT_MAX_LENGTH = 64
RECIPE_MAX_LENGTH_NAME = 256
TAG_MAX_LENGTH = 32

MAX_POSITIVE_VALUE = 32_000

MIN_HASH_GEN = 8
MAX_HASH_GEN = 10
MAX_HASH_LENGTH = 15
URL_MAX_LENGTH = 256
DEFAULT_PAGE_SIZE = 6
