[tool.black]
line-length = 79
target-version = ['py39']
include = '\.pyi?$'
skip-string-normalization = true
extend-exclude = "(migrations|stubs)/"

[tool.isort]
profile = "django"
combine_as_imports = true
include_trailing_comma = true
line_length = 79
multi_line_output = 3
known_first_party = ["api", "core", "recipes", "shortener", "users"]
extend_skip = ["migrations"]
sections = [
    "FUTURE", "STDLIB", "THIRDPARTY",
    "FIRSTPARTY", "LOCALFOLDER",
]
no_lines_before = ["LOCALFOLDER"]
lines_after_imports=2