version: '3.3'

volumes:
  staticfiles:
  mediafiles:
  pg_data:

services:
  db:
    container_name: foodgram-db
    image: postgres:13.10-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h $DB_HOST -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: foodgram-back
    image: mxnoob/foodgram_backend
    volumes:
      - staticfiles:/app/staticfiles/
      - mediafiles:/app/media/
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: foodgram-front
    image: mxnoob/foodgram_frontend
    volumes:
      - staticfiles:/result_build

  nginx:
    container_name: foodgram-proxy
    image: mxnoob/foodgram_nginx
    ports:
      - "8081:80"
    volumes:
      - staticfiles:/staticfiles/
      - mediafiles:/media/
    depends_on:
      - frontend
      - backend
